### ISSUE TITLE
Add close button to Milestone Dialog

### ISSUE THREAD

**Issue by alisonthemonster** [alisonthemonster/GratitudeJournal#90]
Users have requested a close or x button be added to the milestone dialog.

REQUIREMENTS:
- [x] An x button in the top right corner that closes the milestone dialog 
- [x] The x button should be an SVG
- [x] X button should have a content description of "close"
